baseurl = "http://www.matthew-edward-adams.org"
title = "Phantisocracy"
copyright = "Copyright &copy; 2018 Matthew Edward Adams"
canonifyurls = true
theme = "hugo-kiera"

MetaDataFormat = "toml"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Matthew Edward Adams"
    github = "linguistgate"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = "linguistgate"
    instagram = "matthew.e.adams"

[params]
    tagline = "The public workspace of Matthew E. Adams"

[permalinks]
	page = "/:title/"
	about = "/:filename/"